---
abstract: 'dcmp - Compare directories and produce CVS-like output'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Capture::Tiny: '0'
  Encode: '0'
  FindBin: '0'
  POSIX: '0'
  Test::Fatal: '0'
  Test::MockModule: '0'
  Test::More: '0.88'
  Test::TempDir::Tiny: '0'
  autodie: '0'
  constant: '1.01'
  lib: '0'
  perl: '5.006'
  subs: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150005'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-dcmp
no_index:
  directory:
    - corpus
    - dzil-inc
    - examples
    - inc
    - t
    - xt
provides:
  App::DCMP:
    file: bin/dcmp
    version: '0.001'
requires:
  Cwd: '0'
  Digest::MD5: '0'
  File::Compare: '0'
  File::Spec: '0'
  constant: '1.01'
  locale: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/dcmp/issues
  homepage: https://github.com/skirmess/dcmp
  repository: https://github.com/skirmess/dcmp.git
version: '0.001'
x_serialization_backend: 'YAML::Tiny version 1.70'
